Feature/perso details
ldandoy/dd pull request #51
Opened 2022-09-08 13:59 UTC by Fares-B

- Affiche les détails des personnages ainsi que le nom
- Correction lors la création d'un personnage
- Création d'une classe pour gérer les sons et bruitages

2022-09-08 14:11 UTC, BawBaw31 requested changes

2022-09-08 14:11 UTC, BawBaw31 commented on src/Window/character_selection.py
> +    # pygame.mixer.music.play(loops=0)
Supprimer commentaire

2022-09-08 14:47 UTC, yacine-21 approved these changes

2022-09-09 11:21 UTC, BawBaw31 approved these changes

2022-09-09 11:25 UTC, merged