Feature/donjon
ldandoy/dd pull request #53
Opened 2022-09-08 22:36 UTC by yacine-21

2022-09-08 22:36 UTC, yacine-21 commented
Please review my pr :)

2022-09-09 11:38 UTC, BawBaw31 requested changes

2022-09-09 11:38 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    def Playsound(event):
rebase master et utiliser sound utils créé dans la dernière PR

2022-09-09 11:38 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +def QuestChoice():
A quoi ça sert ?

2022-09-09 11:38 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    canvas2 = Canvas(questFrame, width=256, height=144, bd=0, highlightthickness=0)
Pas fan de canvas, canvas1, canvas2. Je préfère une appélation significative :
ex : mainCanvas, titleCanvas, backgroundCanvas, actionCanvas, etc...

2022-09-09 11:38 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    news_Button = Button(canvas2, text="Commencer",
camelCase

2022-09-09 11:38 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    imagePath2 = os.path.join(self.base_folder, '../medias/forgottenTown.png')
Pareil pour l'appélation, ex : backgroundImagePath

2022-09-09 11:38 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +def Quest(self):
c'est quoi self ?

2022-09-09 14:16 UTC, yacine-21 commented on src/Window/QuestScreen.py
> +    imagePath2 = os.path.join(self.base_folder, '../medias/forgottenTown.png')
ok

2022-09-09 14:16 UTC, yacine-21 commented on src/Window/QuestScreen.py
> +    news_Button = Button(canvas2, text="Commencer",
ok

2022-09-09 14:16 UTC, yacine-21 commented on src/Window/QuestScreen.py
> +    canvas2 = Canvas(questFrame, width=256, height=144, bd=0, highlightthickness=0)
ok

2022-09-09 14:17 UTC, yacine-21 commented on src/Window/QuestScreen.py
> +def QuestChoice():
fonction delete

2022-09-09 14:17 UTC, yacine-21 commented on src/Window/QuestScreen.py
> +    def Playsound(event):
ok

2022-09-09 14:19 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    def Playsound(event):
Pas ok :p

2022-09-09 14:19 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    canvas2 = Canvas(questFrame, width=256, height=144, bd=0, highlightthickness=0)
Y a toujours

2022-09-09 14:19 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    news_Button = Button(canvas2, text="Commencer",
y a toujours

2022-09-09 14:20 UTC, BawBaw31 commented on src/Window/QuestScreen.py
> +    imagePath2 = os.path.join(self.base_folder, '../medias/forgottenTown.png')
Y a toujours

2022-09-09 14:31 UTC, closed without merging