feature/quest ending and escape screen
ldandoy/dd pull request #65
Opened 2022-09-29 16:12 UTC by Arthur-Phothirath

New screen for ending and escape from dungeon

2022-09-29 16:24 UTC, yacine-21 requested changes

2022-09-29 16:24 UTC, yacine-21 commented on src/Window/QuestEndingScreen.py
> +    difficultyFont = ('Calibri (Body)', 16, 'bold', 'italic')
change variable name here

2022-09-29 16:24 UTC, yacine-21 commented on src/Window/QuestEscapeScreen.py
> +    difficultyFont = ('Calibri (Body)', 16, 'bold', 'italic')
change name variable too

2022-09-29 16:24 UTC, yacine-21 commented on src/Window/QuestEscapeScreen.py
> +    startButton = Button(questContainer, text="Return to the town", command=choice,
variable name

2022-11-18 13:14 UTC, yacine-21 approved these changes

2022-11-18 13:17 UTC, Maroua1996 approved these changes

2022-11-18 13:18 UTC, merged